<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jan Bos Voorraad</title><link rel="manifest" href="/static/manifest.json"><link rel="stylesheet" href="/static/style.css"></head><body>
<header><div class="brand"><img src="/static/janbos_logo.png" alt="Jan Bos"><div><h1>Voorraad</h1><p>Snel pakken, één tik boeken</p></div></div><button class="primary" onclick="openModal('addModal')">+ Nieuw product</button></header>
<main>
<section class="quick-head"><a class="scan" href="#zoeken">📷 Product zoeken / QR scannen</a><a class="order" href="/?low=1">🔴 {{ low_count }} bijbestellen</a></section>
{% if popular %}<h2 class="section-title">Veel gebruikt</h2><section class="popular-grid">{% for p in popular %}<article class="quick-card {% if p.stock<=p.minimum_stock %}low{% endif %}"><a href="/product/{{p.id}}"><h3>{{p.name}}</h3><div class="bigstock">{{'%g'|format(p.stock)}} <small>{{p.unit}}</small></div><span>{{p.location or 'Geen locatie'}}</span></a><div class="quick-buttons"><form method="post" action="/products/{{p.id}}/quick"><input type="hidden" name="change" value="-1"><button class="minus1">−1</button></form><form method="post" action="/products/{{p.id}}/quick"><input type="hidden" name="change" value="1"><button class="plus1">+1</button></form></div></article>{% endfor %}</section>{% endif %}
<section class="stats"><article><strong>{{total_products}}</strong><span>producten</span></article><article class="warn"><strong>{{low_count}}</strong><span>bijbestellen</span></article><a class="export" href="/export.xlsx">Excel exporteren</a></section>
<form id="zoeken" class="filters" method="get"><input name="q" value="{{q}}" placeholder="Typ product of locatie"><select name="category"><option value="">Alle categorieën</option>{% for c in categories %}<option {% if c==selected_category %}selected{% endif %}>{{c}}</option>{% endfor %}</select><button>Zoeken</button></form>
<section class="product-grid">{% for p in products %}<article class="product {% if p.stock<=p.minimum_stock %}low{% endif %}"><a class="product-link" href="/product/{{p.id}}"><div class="product-top"><div><h2>{{p.name}}</h2><small>{{p.category or 'Product'}} · {{p.location or 'Geen locatie'}}</small></div><span class="status-dot">{% if p.stock<=p.minimum_stock %}BESTELLEN{% else %}OK{% endif %}</span></div><div class="stock"><strong>{{'%g'|format(p.stock)}}</strong><span>{{p.unit}}</span></div></a><div class="fast-four"><form method="post" action="/products/{{p.id}}/quick"><input type="hidden" name="change" value="-1"><button class="out">−1</button></form><form method="post" action="/products/{{p.id}}/quick"><input type="hidden" name="change" value="-5"><button class="out">−5</button></form><form method="post" action="/products/{{p.id}}/quick"><input type="hidden" name="change" value="1"><button class="in">+1</button></form><form method="post" action="/products/{{p.id}}/quick"><input type="hidden" name="change" value="10"><button class="in">+10</button></form></div></article>{% else %}<p class="empty">Nog geen producten gevonden.</p>{% endfor %}</section>
<section class="history"><h2>Laatste wijzigingen</h2><div class="table-wrap"><table><thead><tr><th>Tijd</th><th>Product</th><th>Wijziging</th><th>Voorraad</th></tr></thead><tbody>{% for m in mutations %}<tr><td>{{m.created_at.strftime('%d-%m %H:%M')}}</td><td>{{m.product.name}}</td><td class="{% if m.change>0 %}plus{% else %}minus{% endif %}">{{'+' if m.change>0 else ''}}{{'%g'|format(m.change)}}</td><td>{{'%g'|format(m.stock_after)}}</td></tr>{% else %}<tr><td colspan="4">Nog geen wijzigingen.</td></tr>{% endfor %}</tbody></table></div></section>
</main>
<div class="modal" id="addModal"><div class="box"><button class="close" onclick="closeModal('addModal')">×</button><h2>Product toevoegen</h2><form method="post" action="/products" class="form-grid"><label>Productnaam<input name="name" required></label><label>Categorie<input name="category" placeholder="Kit, tape, verf..."></label><label>Eenheid<select name="unit"><option>stuks</option><option>kokers</option><option>rollen</option><option>dozen</option><option>liter</option><option>kg</option></select></label><label>Locatie<input name="location" placeholder="Stelling B2"></label><label>Beginvoorraad<input name="stock" type="number" step="0.01" value="0"></label><label>Minimumvoorraad<input name="minimum_stock" type="number" step="0.01" value="0"></label><input type="hidden" name="article_number"><input type="hidden" name="notes"><button class="primary wide">Opslaan</button></form></div></div>
<script src="/static/app.js"></script></body></html>
